version: '3.7'

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '3030:3000'
    volumes:
      - ./docker/caddy/CaddyfileDev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  vite:
    image: node:18
    restart: unless-stopped
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: bash -c "npm i && npm run dev"

volumes:
  caddy_data:
    # external: true
  caddy_config:
  node_modules:
