services:
  apache:
    image: httpd:2.4.63
    restart: unless-stopped
    ports:
      - '3030:80'
    volumes:
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./docker/apache/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro

  vite:
    image: node:20
    restart: unless-stopped
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: bash -c "npm i && npm run dev"

volumes:
  node_modules:
