version: '3.7'

services:
  nginx:
    image: nginx:1.23
    restart: unless-stopped
    ports:
      - '3030:3000'
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/:ro

  vite:
    image: node:18
    restart: unless-stopped
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: bash -c "npm i && npm run dev"

volumes:
  node_modules:
