services:
  caddy:
    image: caddy:2.10.0
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./docker/caddy/CaddyfileProd:/etc/caddy/Caddyfile
      - ./dist:/app
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    # external: true
  caddy_config:
