services:
  nginx:
    image: nginx:1.29.4
    restart: unless-stopped
    ports:
      - '3030:3000'
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/:ro

  vite:
    image: node:20
    restart: unless-stopped
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: bash -c "npm i && npm run dev"
    tty: true # to make the logs use colors
    stdin_open: true # to keep the dev server running

volumes:
  node_modules:
