name: lint

env:
  # skip playwright binary install
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      - name: setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: pnpm
      - name: Install deps
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run format
        run: pnpm run format --check
